/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import backEnd.Ingrediente;
import backEnd.Plato;
import backEnd.Restaurante;
import java.io.File;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Caleb
 */
public class AgregarPlato2 extends javax.swing.JFrame {

    private Restaurante administrador;
    private Plato plato;
    private ArrayList array = new ArrayList();
    private DefaultListModel modelo = new DefaultListModel();
    private ArrayList<Ingrediente> ingredientes = new ArrayList<>();

    /**
     * Creates new form AgregarPlato2
     */
    public AgregarPlato2() {
        initComponents();
        this.setLocationRelativeTo(this);
        jListIngredientes.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelImagen = new javax.swing.JLabel();
        jButtonSeleccionarImg = new javax.swing.JButton();
        jButtonAgregarIngrediente = new javax.swing.JButton();
        jButtonEliminarIngrediente = new javax.swing.JButton();
        jLabelIngredientes = new javax.swing.JLabel();
        jTextFieldIngredienteIngresa = new javax.swing.JTextField();
        jTextFieldValorIng = new javax.swing.JTextField();
        jLabelListaActual = new javax.swing.JLabel();
        jScrollPaneContieneLista = new javax.swing.JScrollPane();
        jListIngredientes = new javax.swing.JList<>();
        jButtonGuardarYSalir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabelImagen.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabelImagen.setText("Imagen:");

        jButtonSeleccionarImg.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jButtonSeleccionarImg.setText("Seleccionar imagen");
        jButtonSeleccionarImg.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonSeleccionarImg.setContentAreaFilled(false);
        jButtonSeleccionarImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeleccionarImgActionPerformed(evt);
            }
        });

        jButtonAgregarIngrediente.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jButtonAgregarIngrediente.setText("Agregar");
        jButtonAgregarIngrediente.setToolTipText("Agrega el ingrediente ingresado en el campo ");
        jButtonAgregarIngrediente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonAgregarIngrediente.setContentAreaFilled(false);
        jButtonAgregarIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarIngredienteActionPerformed(evt);
            }
        });

        jButtonEliminarIngrediente.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jButtonEliminarIngrediente.setText("Eliminar");
        jButtonEliminarIngrediente.setToolTipText("Elimina el ingrediente seleccionado de la lista");
        jButtonEliminarIngrediente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonEliminarIngrediente.setContentAreaFilled(false);
        jButtonEliminarIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarIngredienteActionPerformed(evt);
            }
        });

        jLabelIngredientes.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabelIngredientes.setText("Ingredientes:");

        jTextFieldIngredienteIngresa.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jTextFieldIngredienteIngresa.setText("Ingrese aquí nuevos ingredientes");

        jTextFieldValorIng.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jTextFieldValorIng.setText("Ingrese aquí el valor del ingrediente");

        jLabelListaActual.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabelListaActual.setText("Lista actual de ingredientes:");

        jListIngredientes.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jScrollPaneContieneLista.setViewportView(jListIngredientes);

        jButtonGuardarYSalir.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jButtonGuardarYSalir.setText("Guardar y Salir");
        jButtonGuardarYSalir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonGuardarYSalir.setContentAreaFilled(false);
        jButtonGuardarYSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarYSalirActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(247, 178, 6));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Detalles del plato nuevo ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel1)
                .addGap(111, 111, 111)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelIngredientes)
                            .addComponent(jLabelImagen))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSeleccionarImg, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldIngredienteIngresa, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(274, Short.MAX_VALUE)
                        .addComponent(jLabelListaActual)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTextFieldValorIng, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneContieneLista, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAgregarIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEliminarIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addGap(392, 392, 392)
                .addComponent(jButtonGuardarYSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSeleccionarImg, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelImagen))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAgregarIngrediente, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelIngredientes)
                                .addComponent(jTextFieldIngredienteIngresa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jTextFieldValorIng, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelListaActual))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButtonEliminarIngrediente))))
                    .addComponent(jScrollPaneContieneLista, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jButtonGuardarYSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSeleccionarImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeleccionarImgActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG & PNG", "jpg", "png");
        fc.setFileFilter(filter);
        fc.setDialogTitle("Buscar Imagen");
        int regresaValor = fc.showOpenDialog(null);

        if (regresaValor == JFileChooser.APPROVE_OPTION) {
            File archivoElegido = fc.getSelectedFile();
            String direccionArchivo = archivoElegido.getPath();
            try {
                ImageIcon icon = new ImageIcon(direccionArchivo);
                plato.setImagen(icon);
            } catch (Exception es) {
                JOptionPane.showMessageDialog(null, "Error con la imagen" + es);
            }

        }
    }//GEN-LAST:event_jButtonSeleccionarImgActionPerformed

    private void jButtonAgregarIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarIngredienteActionPerformed
        // TODO add your handling code here:
        boolean valorIng;
        valorIng = isNumeric(jTextFieldValorIng.getText());
        if (!valorIng) {
            JOptionPane.showMessageDialog(null, "Ingrese un número en el campo de valor del ingrediente", "Advertencia", 0);
        }
        if (jTextFieldIngredienteIngresa.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "El apartado del nombre del ingrediente está vacío", "Advertencia", 0);
        }
        if (!jTextFieldIngredienteIngresa.getText().isEmpty() && !jTextFieldValorIng.getText().isEmpty() && valorIng) {
            String dato = jTextFieldIngredienteIngresa.getText();
            double valor = Double.parseDouble(jTextFieldValorIng.getText());
            int input = JOptionPane.showConfirmDialog(null, "Desea ingresar el ingrediente " + dato + " con valor: " + jTextFieldValorIng.getText() + " $" + "?");
            if (input == 0) {
                Ingrediente ing = new Ingrediente(dato, valor);
                array.add(dato);
                ingredientes.add(ing);
                plato.setListaIngredientes(ingredientes);
                JOptionPane.showMessageDialog(null, "Ingrediente ingresado con exito");
            } else {
                JOptionPane.showMessageDialog(null, "No se ha agregado el ingrediente");
            }
        }
        modelo.removeAllElements();
        for (int i = 0; i < array.size(); i++) {
            modelo.addElement(array.get(i));
        }
    }//GEN-LAST:event_jButtonAgregarIngredienteActionPerformed

    private void jButtonEliminarIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarIngredienteActionPerformed
        // TODO add your handling code here:
        int input = JOptionPane.showConfirmDialog(null, "Está seguro de eliminar el ingrediente: " + jListIngredientes.getSelectedValue(), "Confirmación", 2);
        if (input == 0) {
            if (plato.buscarIngrediente(jListIngredientes.getSelectedValue()) != null) {
                plato.eliminarIngrediente(jListIngredientes.getSelectedValue());
                array.remove(jListIngredientes.getSelectedValue());
            } else {
                JOptionPane.showMessageDialog(null, "Ingrediente no encontrado en el sistema", "Advertencia", 1);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se ha eliminado el ingrediente");
        }
        modelo.removeAllElements();
        for (int i = 0; i < array.size(); i++) {
            modelo.addElement(array.get(i));
        }
    }//GEN-LAST:event_jButtonEliminarIngredienteActionPerformed

    private void jButtonGuardarYSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarYSalirActionPerformed
        if (plato.getImagen() == null) {
            JOptionPane.showMessageDialog(null, "Recuerde seleccionar una imagen para el platillo", "Advertencia", 0);
        }
        if (plato.getImagen() != null && plato.getListaIngredientes() != null) {
            System.out.println(plato);
            System.out.println(plato.imprimirListaIngredientes());
            JOptionPane.showMessageDialog(null, "Platillo agregado con éxito al sistema!", "Mensaje", 1);
            administrador.getMenu().agregarPlato(plato);
            administrador.getMenu().buscarPlato(plato.getReferencia()).imprimirListaIngredientes();
            EditarMenu i = new EditarMenu();
            i.crear(administrador);
            this.setVisible(false);
            i.setVisible(true);
        }

    }//GEN-LAST:event_jButtonGuardarYSalirActionPerformed
    private static boolean isNumeric(String cadena) {
        try {
            Double.parseDouble(cadena);
            return true;
        } catch (NumberFormatException nfe) {
            return false;
        }
    }

    public void crear(Restaurante r, Plato p1) {
        administrador = r;
        plato = p1;

        //iniciar();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarPlato2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarPlato2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarPlato2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarPlato2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(AgregarPlato2.class.getName()).log(Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarPlato2().setVisible(true);
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(AgregarPlato2.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarIngrediente;
    private javax.swing.JButton jButtonEliminarIngrediente;
    private javax.swing.JButton jButtonGuardarYSalir;
    private javax.swing.JButton jButtonSeleccionarImg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JLabel jLabelIngredientes;
    private javax.swing.JLabel jLabelListaActual;
    private javax.swing.JList<String> jListIngredientes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPaneContieneLista;
    private javax.swing.JTextField jTextFieldIngredienteIngresa;
    private javax.swing.JTextField jTextFieldValorIng;
    // End of variables declaration//GEN-END:variables
}
