/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import backEnd.Ingrediente;
import backEnd.Menu;
import backEnd.Plato;
import backEnd.Restaurante;
import java.io.File;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Caleb
 */
public class AgregarPlato extends javax.swing.JFrame {

    /**
     * Creates new form AgregarPlato
     */
    private Restaurante administrador;

    public AgregarPlato() {
        initComponents();
        this.setLocationRelativeTo(this);

    }

    public void crear(Restaurante r) {
        administrador = r;

        //iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jLabelNombrePlato = new javax.swing.JLabel();
        jLabelDescripcionPlato = new javax.swing.JLabel();
        jLabelValorPlato = new javax.swing.JLabel();
        jTextFieldNombrePlato = new javax.swing.JTextField();
        jTextFieldDescripcionPlato = new javax.swing.JTextField();
        jTextFieldValorPlato = new javax.swing.JTextField();
        jLabelDescuento = new javax.swing.JLabel();
        jTextFieldDescuento = new javax.swing.JTextField();
        jLabelLogoDolar2 = new javax.swing.JLabel();
        jLabelLogoDolar1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonRegresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonGuardar = new javax.swing.JButton();
        jTextFieldNumRef = new javax.swing.JTextField();
        jCheckBoxDescuento = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agregar plato nuevo");
        setResizable(false);

        jPanelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        jLabelNombrePlato.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabelNombrePlato.setText("Nombre del plato:");

        jLabelDescripcionPlato.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabelDescripcionPlato.setText("Descripción del plato:");

        jLabelValorPlato.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabelValorPlato.setText("Valor:");

        jTextFieldNombrePlato.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jTextFieldNombrePlato.setText("Ingrese el nombre del plato");

        jTextFieldDescripcionPlato.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jTextFieldDescripcionPlato.setText("Ingrese la descripción del plato");

        jTextFieldValorPlato.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jTextFieldValorPlato.setText("Ej: 5.50");

        jLabelDescuento.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabelDescuento.setText("Descuento:");

        jTextFieldDescuento.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jTextFieldDescuento.setText("Ingrese el descuento a aplicar");

        jLabelLogoDolar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/iconoDolarSi.jpg"))); // NOI18N

        jLabelLogoDolar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/iconoDolarSi.jpg"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(247, 178, 6));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/logo.png"))); // NOI18N

        jButtonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/flecha.png"))); // NOI18N
        jButtonRegresar.setContentAreaFilled(false);
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Agregar plato al menú");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel1)
                .addGap(82, 82, 82)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonRegresar)
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jButtonRegresar)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel3.setText("Número de referencia: ");

        jButtonGuardar.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jButtonGuardar.setText("Continuar a detallar el plato");
        jButtonGuardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonGuardar.setContentAreaFilled(false);
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jTextFieldNumRef.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jTextFieldNumRef.setText("Ej: 1809");

        jCheckBoxDescuento.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jCheckBoxDescuento.setText("Habilitar descuento");
        jCheckBoxDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxDescuentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                                .addComponent(jLabelDescuento)
                                .addGap(147, 147, 147)
                                .addComponent(jTextFieldDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelLogoDolar2)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBoxDescuento))
                            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelPrincipalLayout.createSequentialGroup()
                                        .addComponent(jLabelDescripcionPlato)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextFieldDescripcionPlato, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelPrincipalLayout.createSequentialGroup()
                                        .addComponent(jLabelNombrePlato)
                                        .addGap(90, 90, 90)
                                        .addComponent(jTextFieldNombrePlato, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelValorPlato)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldValorPlato, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                                            .addComponent(jTextFieldNumRef))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelLogoDolar1))))
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGap(362, 362, 362)
                        .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombrePlato)
                    .addComponent(jTextFieldNombrePlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDescripcionPlato)
                    .addComponent(jTextFieldDescripcionPlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldNumRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelValorPlato)
                            .addComponent(jTextFieldValorPlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelLogoDolar2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelDescuento)
                                .addComponent(jTextFieldDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jCheckBoxDescuento, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(39, 39, 39)
                        .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabelLogoDolar1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        // TODO add your handling code here:
        EditarMenu i = new EditarMenu();
        i.crear(administrador);
        this.setVisible(false);
        i.setVisible(true);

    }//GEN-LAST:event_jButtonRegresarActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
        boolean valorPlato;
        boolean valorDesc;
        boolean referencia;
        referencia = isNumeric(jTextFieldNumRef.getText());
        valorPlato = isNumeric(jTextFieldValorPlato.getText());
        valorDesc = isNumeric(jTextFieldDescuento.getText());
        if (jTextFieldNombrePlato.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "El apartado de nombre del plato esta vacio", "Advertencia", 0);
        }
        if (jTextFieldDescripcionPlato.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "El apartado de la descripción del plato esta vacio", "Advertencia", 0);
        }
        if (jTextFieldValorPlato.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "El apartado del valor del plato esta vacio", "Advertencia", 0);
        }
        if (!valorPlato) {
            JOptionPane.showMessageDialog(null, "Ingrese un número en el campo del valor del plato", "Advertencia", 0);
        }
        if (!valorDesc) {
            JOptionPane.showMessageDialog(null, "Ingrese un número en el campo de valor del descuento", "Advertencia", 0);
        }
        if (!validarDescuento()) {
            JOptionPane.showMessageDialog(null, "El descuento no puede ser mayor o igual al valor del platillo", "Advertencia", 0);
        }

        if (!referencia) {
            JOptionPane.showMessageDialog(null, "Ingrese un número en el campo del valor de referencia del plato", "Advertencia", 0);
        }

        if (!validarPlato()) {
            JOptionPane.showMessageDialog(null, "El plato ya existe en el sistema", "Advertencia", 0);
        }
        if (!jTextFieldNombrePlato.getText().isEmpty() && !jTextFieldDescripcionPlato.getText().isEmpty() && !jTextFieldValorPlato.getText().isEmpty() && !jTextFieldDescuento.getText().isEmpty() && valorPlato && valorDesc && validarDescuento() && validarPlato() && referencia) {
            Plato p1 = new Plato(jTextFieldNombrePlato.getText(), jTextFieldDescripcionPlato.getText(), Double.parseDouble(jTextFieldValorPlato.getText()),Integer.parseInt(jTextFieldNumRef.getText()));
            if(jCheckBoxDescuento.isSelected()){
               p1.setDescuento(Double.parseDouble(jTextFieldDescuento.getText()));
               //p1.calcularValorConDescuento(Double.parseDouble(jTextFieldDescuento.getText()));
               
            }else{
               p1.setDescuento(0);
            }
            //p1.calcularValorConDescuento(Double.parseDouble(jTextFieldDescuento.getText()));
            AgregarPlato2 i = new AgregarPlato2();
            i.crear(administrador, p1);
            this.setVisible(false);
            i.setVisible(true);
        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jCheckBoxDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxDescuentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxDescuentoActionPerformed

    private boolean validarDescuento() {
        boolean retornar = true;
        if (isNumeric(jTextFieldDescuento.getText())) {
            if (Double.parseDouble(jTextFieldDescuento.getText()) >= Double.parseDouble(jTextFieldValorPlato.getText())) {
                retornar = false;
                return retornar;
            } else {
                return retornar;
            }
        }
        retornar = false;
        return retornar;
    }

    private boolean validarPlato() {
        boolean retornar = true;

        if (administrador.getMenu().buscarPlato(Integer.parseInt(jTextFieldNumRef.getText())) != null) {
            retornar = false;
            return retornar;
        } else {
            return retornar;
        }

    }

    private static boolean isNumeric(String cadena) {
        try {
            Double.parseDouble(cadena);
            return true;
        } catch (NumberFormatException nfe) {
            return false;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarPlato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarPlato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarPlato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarPlato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarPlato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JCheckBox jCheckBoxDescuento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelDescripcionPlato;
    private javax.swing.JLabel jLabelDescuento;
    private javax.swing.JLabel jLabelLogoDolar1;
    private javax.swing.JLabel jLabelLogoDolar2;
    private javax.swing.JLabel jLabelNombrePlato;
    private javax.swing.JLabel jLabelValorPlato;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JTextField jTextFieldDescripcionPlato;
    private javax.swing.JTextField jTextFieldDescuento;
    private javax.swing.JTextField jTextFieldNombrePlato;
    private javax.swing.JTextField jTextFieldNumRef;
    private javax.swing.JTextField jTextFieldValorPlato;
    // End of variables declaration//GEN-END:variables
}
