/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import backEnd.Restaurante;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Caleb
 */
public class GestionarRestaurante extends javax.swing.JFrame {

    private Restaurante administrador;
    private ArrayList array = new ArrayList();
    private DefaultListModel modelo = new DefaultListModel();

    /**
     * Creates new form GestionarRestaurante
     */
    public GestionarRestaurante() {
        initComponents();
        this.setLocationRelativeTo(this);
        jListClientesReserva.setModel(modelo);
    }

    public boolean existeLista(DefaultListModel modelo, String dato) {
        boolean validar = false;
        for (int i = 0; i < modelo.getSize(); i++) {
            if (modelo.getElementAt(i).equals(dato)) {
                validar = true;
            }
        }
        return validar;
    }

    public void llenar(Restaurante administrador) throws Exception {
        SimpleDateFormat dt1 = new SimpleDateFormat("yyyy-MM-dd");
        for (int j = 0; j < administrador.getClientes().contar(); j++) {
            if (administrador.getClientes().valorIndice(j).getVerificacionReserva()) {
                Date fecha = administrador.getClientes().valorIndice(j).getReserva().getFechaReserva();
                array.add(administrador.getClientes().valorIndice(j).getNombre() + " para el día: " + dt1.format(fecha));
            }
        }
        modelo.removeAllElements();
        for (int i = 0; i < array.size(); i++) {
            if(!existeLista(modelo, array.get(i).toString())){
            modelo.addElement(array.get(i));
            }
        }
        jLabelNumPersonas.setText(String.valueOf(administrador.getAforoAct()-1));
        jTextFieldAforo.setText(String.valueOf(administrador.getAforoMax()));
        jTextArea1.setText(administrador.getPoliticas());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jLabelAforo = new javax.swing.JLabel();
        jTextFieldAforo = new javax.swing.JTextField();
        jLabelNumPersonas = new javax.swing.JLabel();
        jLabelPersonas = new javax.swing.JLabel();
        jLabelClientesReserva = new javax.swing.JLabel();
        jScrollPaneContieneLista = new javax.swing.JScrollPane();
        jListClientesReserva = new javax.swing.JList<>();
        jLabelModificarPoliticas = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonRegresar = new javax.swing.JButton();
        jButtonGuardarYSalir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestionar restaurante");
        setResizable(false);

        jPanelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        jLabelAforo.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabelAforo.setText("Aforo establecido:");

        jTextFieldAforo.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N

        jLabelNumPersonas.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabelNumPersonas.setText("jLabel1");

        jLabelPersonas.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabelPersonas.setText("Número de personas en el restaurante actualmente:");

        jLabelClientesReserva.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabelClientesReserva.setText("Clientes con reserva:");

        jListClientesReserva.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jListClientesReserva.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneContieneLista.setViewportView(jListClientesReserva);

        jLabelModificarPoliticas.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabelModificarPoliticas.setText("Modificar politicas internas:");

        jPanel2.setBackground(new java.awt.Color(247, 178, 6));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/logo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Gestión del Pacífico");

        jButtonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/flecha.png"))); // NOI18N
        jButtonRegresar.setContentAreaFilled(false);
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1)
                .addGap(93, 93, 93)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addComponent(jButtonRegresar)
                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jButtonRegresar))
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jButtonGuardarYSalir.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jButtonGuardarYSalir.setText("Guardar y Salir");
        jButtonGuardarYSalir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonGuardarYSalir.setContentAreaFilled(false);
        jButtonGuardarYSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarYSalirActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                                .addComponent(jLabelAforo)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldAforo, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                                .addComponent(jLabelPersonas)
                                .addGap(35, 35, 35)
                                .addComponent(jLabelNumPersonas))
                            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelModificarPoliticas)
                                    .addComponent(jLabelClientesReserva))
                                .addGap(33, 33, 33)
                                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPaneContieneLista)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)))))
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(jButtonGuardarYSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAforo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAforo))
                .addGap(26, 26, 26)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNumPersonas, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelPersonas, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabelClientesReserva)
                        .addGap(89, 89, 89))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPaneContieneLista, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelModificarPoliticas)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jButtonGuardarYSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarYSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarYSalirActionPerformed
        // TODO add your handling code here:
        boolean validarAforo;
        validarAforo = isNumeric(jTextFieldAforo.getText());
        if (jTextFieldAforo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese un valor en el campo del aforo por favor", "Advertencia", 1);
        }
        if (!validarAforo) {
            JOptionPane.showMessageDialog(null, "Ingrese un número en el campo del aforo por favor", "Advertencia", 1);
        }
        if (jTextArea1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Recuerde ingresar las politicas internas del restaurante", "Advertencia", 1);
        }
        if (!jTextFieldAforo.getText().isEmpty() && validarAforo && !jTextArea1.getText().isEmpty()) {
            administrador.setAforoMax(Integer.parseInt(jTextFieldAforo.getText()));
            administrador.setPoliticas(jTextArea1.getText());
            System.out.println(administrador.getPoliticas());
            System.out.println(administrador.getAforoMax());
            InterfazAdmin i = new InterfazAdmin();
            i.crear(administrador);
            this.setVisible(false);
            i.setVisible(true);
        }
    }//GEN-LAST:event_jButtonGuardarYSalirActionPerformed

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        // TODO add your handling code here:
        InterfazAdmin i = new InterfazAdmin();
        i.crear(administrador);
        this.setVisible(false);
        i.setVisible(true);
    }//GEN-LAST:event_jButtonRegresarActionPerformed
    private static boolean isNumeric(String cadena) {
        try {
            Integer.parseInt(cadena);
            return true;
        } catch (NumberFormatException nfe) {
            return false;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionarRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionarRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionarRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionarRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionarRestaurante().setVisible(true);
            }
        });
    }

    public void crear(Restaurante r) {
        administrador = r;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGuardarYSalir;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAforo;
    private javax.swing.JLabel jLabelClientesReserva;
    private javax.swing.JLabel jLabelModificarPoliticas;
    private javax.swing.JLabel jLabelNumPersonas;
    private javax.swing.JLabel jLabelPersonas;
    private javax.swing.JList<String> jListClientesReserva;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPaneContieneLista;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldAforo;
    // End of variables declaration//GEN-END:variables
}
