/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import backEnd.Cliente;
import backEnd.Ingrediente;
import backEnd.Pedido;
import backEnd.Plato;
import backEnd.Restaurante;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;

/**
 *
 * @author Chaval
 */
public class LoginPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    private Restaurante administrador;

    public LoginPrincipal() {
        initComponents();
        
        this.setLocationRelativeTo(this);
        administrador = new Restaurante("admin123", "Administrador");
        Date f = new Date(2021 - 1900, 11-1, 12);
        Cliente c2 = new Cliente("José Perez", "1850124783", 0, "0992927124");
        Cliente c3 = new Cliente("Benito Martínez", "1711070043",0, "09982832674");
        Cliente c4 = new Cliente("Cliente nuevo", "1802758746", 0, "09982832674");
        c2.reservar(f);
        Date f2 = new Date(2021-1900, 12-1, 25);
        c3.reservar(f2);

        ArrayList<Ingrediente> listaIngredientes = new ArrayList();
        Ingrediente i1 = new Ingrediente("pan", 1.50);
        Ingrediente i2 = new Ingrediente("queso", 0.50);

        ArrayList<Ingrediente> listaIngredientes2 = new ArrayList();
        Ingrediente i3 = new Ingrediente("pan", 2.00);
        Ingrediente i4 = new Ingrediente("carne de res", 3.00);
        Ingrediente i5 = new Ingrediente("lechuga", 0.10);
        Ingrediente i6 = new Ingrediente("queso", 0.10);

        ArrayList<Ingrediente> listaIngredientes3 = new ArrayList();
        Ingrediente i7 = new Ingrediente("pan", 1.00);
        Ingrediente i8 = new Ingrediente("salchicha", 2.00);

        ArrayList<Ingrediente> listaIngredientes4 = new ArrayList();
        Ingrediente i9 = new Ingrediente("leche", 3.00);
        Ingrediente i10 = new Ingrediente("pasas", 2.00);

        listaIngredientes.add(i1);
        listaIngredientes.add(i2);
        
        listaIngredientes2.add(i3);
        listaIngredientes2.add(i4);
        listaIngredientes2.add(i5);
        listaIngredientes2.add(i6);

        listaIngredientes3.add(i7);
        listaIngredientes3.add(i8);
        
        listaIngredientes4.add(i9);
        listaIngredientes4.add(i10);
        
        Plato p1 = new Plato("Pan con queso", "Pan con un queso americano dentro", 5.50, listaIngredientes, 0, new ImageIcon(getClass().getResource("/Imagenes/panConQuesoBien.png")),1);
        Plato p2 = new Plato("Hamburguesa", "Hamburguesa con carne a la parrilla", 5, listaIngredientes2, 2, new ImageIcon(getClass().getResource("/Imagenes/imagenHamburguesa.jpg")),10);
        Plato p3 = new Plato("Hot-Dog", "Salchicha entre dos panes", 8, listaIngredientes3, 3, new ImageIcon(getClass().getResource("/Imagenes/hotDogBien.png")),11);
        Plato p4 = new Plato("Helado", "Helado cremoso", 10, listaIngredientes4, 5, new ImageIcon(getClass().getResource("/Imagenes/imgHeladoBien.png")),100);

        
        administrador.getMenu().agregarPlato(p1);
        administrador.getMenu().agregarPlato(p2);
        administrador.getMenu().agregarPlato(p3);
        administrador.getMenu().agregarPlato(p4);

        String politicas = "1.Mantener las medidas de bioseguridad\n2.Ofrecer un servicio al "
                + "cliente óptimo" + "\n3.Proponer un estándar de restaurantes";
        administrador.setPoliticas(politicas);
        Pedido pedido = new Pedido();
        pedido.agregarPlatoPedido(p1);
        pedido.agregarPlatoPedido(p4);
        Pedido pedido2 = new Pedido();
        pedido2.agregarPlatoPedido(p3);
        pedido2.agregarPlatoPedido(p2);
        c2.setPedidos(pedido);
        c3.setPedidos(pedido2);
        c4.setPedidos(pedido2);
        administrador.agregarCliente(c2);
        administrador.agregarCliente(c3);
        administrador.agregarCliente(c4);
        administrador.setAforoAct(administrador.getClientes().contar());
        administrador.getClientes().imprimir();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Administrador = new javax.swing.JLabel();
        Cliente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login principal");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(247, 178, 6));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PacificApp");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Administrador.setBackground(new java.awt.Color(255, 255, 255));
        Administrador.setFont(new java.awt.Font("Ebrima", 0, 36)); // NOI18N
        Administrador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Administrador.setText("Administrador");
        Administrador.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Administrador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Administrador.setOpaque(true);
        Administrador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdministradorMouseClicked(evt);
            }
        });

        Cliente.setBackground(new java.awt.Color(255, 255, 255));
        Cliente.setFont(new java.awt.Font("Ebrima", 0, 36)); // NOI18N
        Cliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cliente.setText("Cliente");
        Cliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Cliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cliente.setOpaque(true);
        Cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClienteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Administrador, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(Administrador, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdministradorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdministradorMouseClicked
        // TODO add your handling code here:
        loginAdmin a = new loginAdmin();
        a.crear(administrador);
        a.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_AdministradorMouseClicked

    private void ClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClienteMouseClicked
        // TODO add your handling code here:
        LoginCliente l = new LoginCliente();
        l.crear(administrador);
        l.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ClienteMouseClicked

    public void crear(Restaurante r) {
        administrador = r;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Administrador;
    private javax.swing.JLabel Cliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
