/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import backEnd.Cliente;
import backEnd.Ingrediente;
import backEnd.Menu;
import backEnd.Plato;
import backEnd.Restaurante;
import java.io.File;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Caleb
 */
public class ModificarPlato extends javax.swing.JFrame {

    /**
     * Creates new form ModificarPlato
     */
    private Restaurante administrador;
    private Plato p;
    private ArrayList array = new ArrayList();
    private DefaultListModel modelo = new DefaultListModel();

    public ModificarPlato() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    public void crear(Restaurante r, Plato p1) {
        administrador = r;
        p = p1;
        //iniciar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jLabelNombrePlato = new javax.swing.JLabel();
        jTextFieldNombrePlato = new javax.swing.JTextField();
        jLabelDescripcionPlato = new javax.swing.JLabel();
        jTextFieldDescripcionPlato = new javax.swing.JTextField();
        jLabelValorPlato = new javax.swing.JLabel();
        jTextFieldValorPlato = new javax.swing.JTextField();
        jLabelLogoDolar = new javax.swing.JLabel();
        jLabelIngredientes = new javax.swing.JLabel();
        jButtonGuardarYSalir = new javax.swing.JButton();
        jLabelDescuento = new javax.swing.JLabel();
        jTextFieldDescuento = new javax.swing.JTextField();
        jLabelLogoDolar2 = new javax.swing.JLabel();
        jLabelImagen = new javax.swing.JLabel();
        jButtonSeleccionarImg = new javax.swing.JButton();
        jScrollPaneContenedorLista = new javax.swing.JScrollPane();
        jListIngredientes = new javax.swing.JList<>();
        jButtonAgregarIngrediente = new javax.swing.JButton();
        jTextFieldIngredienteIngresa = new javax.swing.JTextField();
        jLabelListaActualIng = new javax.swing.JLabel();
        jButtonEliminarIngrediente = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextFieldValorIng = new javax.swing.JTextField();
        jButtonPrevisualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Modificar plato");
        setResizable(false);

        jPanelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        jPanelPrincipal.setForeground(new java.awt.Color(255, 255, 255));

        jLabelNombrePlato.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabelNombrePlato.setText("Nombre del plato:");

        jTextFieldNombrePlato.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N

        jLabelDescripcionPlato.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabelDescripcionPlato.setText("Descripción del plato:");

        jTextFieldDescripcionPlato.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jTextFieldDescripcionPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDescripcionPlatoActionPerformed(evt);
            }
        });

        jLabelValorPlato.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabelValorPlato.setText("Valor:");

        jTextFieldValorPlato.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jTextFieldValorPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValorPlatoActionPerformed(evt);
            }
        });

        jLabelLogoDolar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/iconoDolarSi.jpg"))); // NOI18N

        jLabelIngredientes.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabelIngredientes.setText("Ingredientes:");

        jButtonGuardarYSalir.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jButtonGuardarYSalir.setText("Guardar y Salir");
        jButtonGuardarYSalir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonGuardarYSalir.setContentAreaFilled(false);
        jButtonGuardarYSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarYSalirActionPerformed(evt);
            }
        });

        jLabelDescuento.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabelDescuento.setText("Descuento:");

        jTextFieldDescuento.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N

        jLabelLogoDolar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/iconoDolarSi.jpg"))); // NOI18N

        jLabelImagen.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabelImagen.setText("Imagen:");

        jButtonSeleccionarImg.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jButtonSeleccionarImg.setText("Seleccionar imagen");
        jButtonSeleccionarImg.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonSeleccionarImg.setContentAreaFilled(false);
        jButtonSeleccionarImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeleccionarImgActionPerformed(evt);
            }
        });

        jListIngredientes.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        jListIngredientes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneContenedorLista.setViewportView(jListIngredientes);

        jButtonAgregarIngrediente.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jButtonAgregarIngrediente.setText("Agregar");
        jButtonAgregarIngrediente.setToolTipText("Agrega el ingrediente ingresado en el campo ");
        jButtonAgregarIngrediente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonAgregarIngrediente.setContentAreaFilled(false);
        jButtonAgregarIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarIngredienteActionPerformed(evt);
            }
        });

        jTextFieldIngredienteIngresa.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jTextFieldIngredienteIngresa.setText("Ingrese aquí nuevos ingredientes");

        jLabelListaActualIng.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabelListaActualIng.setText("Lista actual de ingredientes:");

        jButtonEliminarIngrediente.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jButtonEliminarIngrediente.setText("Eliminar");
        jButtonEliminarIngrediente.setToolTipText("Elimina el ingrediente seleccionado en la lista");
        jButtonEliminarIngrediente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonEliminarIngrediente.setContentAreaFilled(false);
        jButtonEliminarIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarIngredienteActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(247, 178, 6));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/logo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Modificar plato del menú");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/flecha.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel1)
                .addGap(110, 110, 110)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(57, 57, 57))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 11, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(35, 35, 35))))
        );

        jTextFieldValorIng.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jTextFieldValorIng.setText("Ingrese el valor del ingrediente a agregar");

        jButtonPrevisualizar.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jButtonPrevisualizar.setText("Previsualizar imagen");
        jButtonPrevisualizar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonPrevisualizar.setContentAreaFilled(false);
        jButtonPrevisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrevisualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNombrePlato)
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelIngredientes)
                            .addComponent(jLabelDescuento)
                            .addComponent(jLabelImagen)
                            .addComponent(jLabelValorPlato)
                            .addComponent(jLabelDescripcionPlato))
                        .addGap(46, 46, 46)
                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                                .addComponent(jTextFieldValorPlato, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelLogoDolar)
                                .addGap(106, 106, 106))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipalLayout.createSequentialGroup()
                                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldIngredienteIngresa)
                                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                                        .addComponent(jLabelListaActualIng)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jTextFieldValorIng))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPaneContenedorLista, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonAgregarIngrediente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonEliminarIngrediente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldDescripcionPlato, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldNombrePlato, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                                        .addComponent(jTextFieldDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelLogoDolar2))
                                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                                        .addComponent(jButtonPrevisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonSeleccionarImg, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(159, 159, 159)
                                        .addComponent(jButtonGuardarYSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(36, 36, 36))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNombrePlato)
                    .addComponent(jTextFieldNombrePlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldDescripcionPlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDescripcionPlato))
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabelIngredientes))
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldValorPlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelValorPlato))
                            .addComponent(jLabelLogoDolar))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                                .addComponent(jButtonAgregarIngrediente)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonEliminarIngrediente))
                            .addComponent(jScrollPaneContenedorLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                                .addComponent(jTextFieldIngredienteIngresa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldValorIng, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelListaActualIng)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelDescuento))
                    .addComponent(jLabelLogoDolar2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(31, 31, 31)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelImagen)
                    .addComponent(jButtonSeleccionarImg, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGuardarYSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPrevisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDescripcionPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDescripcionPlatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDescripcionPlatoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        EditarMenu i = new EditarMenu();
        i.crear(administrador);
        this.setVisible(false);
        i.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonGuardarYSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarYSalirActionPerformed
        // TODO add your handling code here:
        boolean valorPlato;
        boolean valorDesc;
        valorPlato = isNumeric(jTextFieldValorPlato.getText());
        valorDesc = isNumeric(jTextFieldDescuento.getText());
        if (jTextFieldNombrePlato.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "El apartado de nombre del plato esta vacio", "Advertencia", 0);
        }
        if (jTextFieldDescripcionPlato.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "El apartado de la descripción del plato esta vacio", "Advertencia", 0);
        }
        if (jTextFieldValorPlato.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "El apartado del valor del plato esta vacio", "Advertencia", 0);
        }
        if (!jTextFieldNombrePlato.getText().isEmpty() && !jTextFieldDescripcionPlato.getText().isEmpty() && !jTextFieldValorPlato.getText().isEmpty() && valorPlato && valorDesc && validarDescuento()) {
            System.out.println("INGRESA");
            modificar();
            System.out.println(p.toString());
            EditarMenu i = new EditarMenu();
            i.crear(administrador);
            this.setVisible(false);
            i.setVisible(true);
        }


    }//GEN-LAST:event_jButtonGuardarYSalirActionPerformed
    private boolean validarDescuento() {
        boolean retornar = true;
        if (isNumeric(jTextFieldDescuento.getText())) {
            if (Double.parseDouble(jTextFieldDescuento.getText()) >= Double.parseDouble(jTextFieldValorPlato.getText())) {
                retornar = false;
                return retornar;
            } else {
                return retornar;
            }
        }
        retornar = false;
        return retornar;
    }


    private void jTextFieldValorPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValorPlatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValorPlatoActionPerformed

    private void jButtonAgregarIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarIngredienteActionPerformed
        // TODO add your handling code here:
        boolean valorIng;
        valorIng = isNumeric(jTextFieldValorIng.getText());
        if (!valorIng) {
            JOptionPane.showMessageDialog(null, "Ingrese un número en el campo de valor del ingrediente", "Advertencia", 0);
        }
        if (jTextFieldIngredienteIngresa.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "El apartado del nombre del ingrediente está vacío", "Advertencia", 0);
        }
        if (!jTextFieldIngredienteIngresa.getText().isEmpty() && !jTextFieldValorIng.getText().isEmpty() && valorIng) {
            
            String dato = jTextFieldIngredienteIngresa.getText();
            double valor = Double.parseDouble(jTextFieldValorIng.getText());
            int input = JOptionPane.showConfirmDialog(null, "Desea ingresar el ingrediente "+ dato+ " con valor: "+ jTextFieldValorIng.getText()+ " $"+ "?");
            if(input==0){
            Ingrediente ing = new Ingrediente(dato, valor);
            array.add(dato);
            p.getListaIngredientes().add(ing);
            JOptionPane.showMessageDialog(null, "Ingrediente ingresado con exito");
            }else{
                 JOptionPane.showMessageDialog(null, "No se ha agregado el ingrediente");
            }
        }
        modelo.removeAllElements();
        for (int i = 0; i < array.size(); i++) {
            modelo.addElement(array.get(i));
        }
    }//GEN-LAST:event_jButtonAgregarIngredienteActionPerformed

    private void jButtonPrevisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrevisualizarActionPerformed
        // TODO add your handling code here:
        JPanel panel = new JPanel();
        JLabel label = new JLabel(p.getImagen());
        panel.add(label);
        JOptionPane.showMessageDialog(null, panel);
    }//GEN-LAST:event_jButtonPrevisualizarActionPerformed

    private void jButtonSeleccionarImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeleccionarImgActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG & PNG", "jpg", "png");

        fc.setFileFilter(filter);
        fc.setDialogTitle("Buscar Imagen");
        int regresaValor = fc.showOpenDialog(null);

        if (regresaValor == JFileChooser.APPROVE_OPTION) {
            File archivoElegido = fc.getSelectedFile();
            String direccionArchivo = archivoElegido.getPath();
            try {
                ImageIcon icon = new ImageIcon(direccionArchivo);
                p.setImagen(icon);
            } catch (Exception es) {
                JOptionPane.showMessageDialog(null, "Error con la imagen" + es);
            }

        }
    }//GEN-LAST:event_jButtonSeleccionarImgActionPerformed

    private void jButtonEliminarIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarIngredienteActionPerformed
        // TODO add your handling code here:
        int input = JOptionPane.showConfirmDialog(null, "Está seguro de eliminar el ingrediente: " + jListIngredientes.getSelectedValue(), "Confirmación", 2);
        if (input == 0) {
            if (p.buscarIngrediente(jListIngredientes.getSelectedValue()) != null) {
                p.eliminarIngrediente(jListIngredientes.getSelectedValue());
                array.remove(jListIngredientes.getSelectedValue());
            } else {
                JOptionPane.showMessageDialog(null, "Ingrediente no encontrado en el sistema", "Advertencia", 1);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se ha eliminado el ingrediente");
        }
        modelo.removeAllElements();
        for (int i = 0; i < array.size(); i++) {
            modelo.addElement(array.get(i));
        }
    }//GEN-LAST:event_jButtonEliminarIngredienteActionPerformed

    public void modificar() {
        p.setNombre(jTextFieldNombrePlato.getText());
        p.setDescripcion(jTextFieldDescripcionPlato.getText());
        p.setDescuento(Double.parseDouble(jTextFieldDescuento.getText()));
        p.setValor(Double.parseDouble(jTextFieldValorPlato.getText()));
        p.calcularValorConDescuento(Double.parseDouble(jTextFieldDescuento.getText()));
    }

    public void llenar() {
        jTextFieldNombrePlato.setText(p.getNombre());
        jTextFieldDescripcionPlato.setText(p.getDescripcion());
        jTextFieldValorPlato.setText(String.valueOf(p.getValor()));
        jTextFieldDescuento.setText(String.valueOf(p.getDescuento()));
        jListIngredientes.setModel(modelo);
        //array = p.getListaIngredientes();
        for (int j = 0; j < p.getListaIngredientes().size(); j++) {
            String nombreIngredientes;
            nombreIngredientes = (String) p.getListaIngredientes().get(j).getNombre();
            array.add(nombreIngredientes);
        }
        modelo.removeAllElements();
        for (int i = 0; i < array.size(); i++) {
            modelo.addElement(array.get(i));
        }
    }

    private static boolean isNumeric(String cadena) {
        try {
            Double.parseDouble(cadena);
            return true;
        } catch (NumberFormatException nfe) {
            return false;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarPlato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarPlato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarPlato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarPlato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarPlato().setVisible(true);

                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(AgregarPlato2.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(AgregarPlato2.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(AgregarPlato2.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(AgregarPlato2.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAgregarIngrediente;
    private javax.swing.JButton jButtonEliminarIngrediente;
    private javax.swing.JButton jButtonGuardarYSalir;
    private javax.swing.JButton jButtonPrevisualizar;
    private javax.swing.JButton jButtonSeleccionarImg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelDescripcionPlato;
    private javax.swing.JLabel jLabelDescuento;
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JLabel jLabelIngredientes;
    private javax.swing.JLabel jLabelListaActualIng;
    private javax.swing.JLabel jLabelLogoDolar;
    private javax.swing.JLabel jLabelLogoDolar2;
    private javax.swing.JLabel jLabelNombrePlato;
    private javax.swing.JLabel jLabelValorPlato;
    private javax.swing.JList<String> jListIngredientes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JScrollPane jScrollPaneContenedorLista;
    private javax.swing.JTextField jTextFieldDescripcionPlato;
    private javax.swing.JTextField jTextFieldDescuento;
    private javax.swing.JTextField jTextFieldIngredienteIngresa;
    private javax.swing.JTextField jTextFieldNombrePlato;
    private javax.swing.JTextField jTextFieldValorIng;
    private javax.swing.JTextField jTextFieldValorPlato;
    // End of variables declaration//GEN-END:variables
}
