/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import backEnd.Cliente;
import backEnd.Restaurante;
import java.awt.Frame;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Dell
 */
public class Politicas extends javax.swing.JFrame {

    private Restaurante administrador;
    private Cliente cliente;
    
    public Politicas() {
        initComponents();
      }
    
    public void crear(Restaurante r, Cliente c) {
        administrador = r;
        cliente = c;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabelMinimizar1 = new javax.swing.JLabel();
        jLabelBotonCerrar1 = new javax.swing.JLabel();
        jButtonRegresarMenu = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabelMinimizar2 = new javax.swing.JLabel();
        jLabelBotonCerrar2 = new javax.swing.JLabel();
        jButtonRegresarMenu1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaPoliticas = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(253, 200, 35));
        jPanel4.setPreferredSize(new java.awt.Dimension(400, 31));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMinimizar1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelMinimizar1.setForeground(new java.awt.Color(51, 204, 0));
        jLabelMinimizar1.setText("•");
        jLabelMinimizar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimizar1MouseClicked(evt);
            }
        });
        jPanel4.add(jLabelMinimizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 30, 30));

        jLabelBotonCerrar1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelBotonCerrar1.setForeground(new java.awt.Color(255, 0, 0));
        jLabelBotonCerrar1.setText("•");
        jLabelBotonCerrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBotonCerrar1MouseClicked(evt);
            }
        });
        jPanel4.add(jLabelBotonCerrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 30, 30));

        jButtonRegresarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/flecha.png"))); // NOI18N
        jButtonRegresarMenu.setContentAreaFilled(false);
        jButtonRegresarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarMenuActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonRegresarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 30));

        jPanel1.setBackground(new java.awt.Color(247, 178, 6));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(200, 194, 194));
        jLabel2.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(252, 250, 250));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Politicas");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 220, 76));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 90));

        jPanel5.setBackground(new java.awt.Color(253, 200, 35));
        jPanel5.setPreferredSize(new java.awt.Dimension(400, 31));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMinimizar2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelMinimizar2.setForeground(new java.awt.Color(51, 204, 0));
        jLabelMinimizar2.setText("•");
        jLabelMinimizar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimizar2MouseClicked(evt);
            }
        });
        jPanel5.add(jLabelMinimizar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 30, 30));

        jLabelBotonCerrar2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelBotonCerrar2.setForeground(new java.awt.Color(255, 0, 0));
        jLabelBotonCerrar2.setText("•");
        jLabelBotonCerrar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBotonCerrar2MouseClicked(evt);
            }
        });
        jPanel5.add(jLabelBotonCerrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 30, 30));

        jButtonRegresarMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/flecha.png"))); // NOI18N
        jButtonRegresarMenu1.setContentAreaFilled(false);
        jButtonRegresarMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarMenu1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonRegresarMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 140));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTextAreaPoliticas.setEditable(false);
        jTextAreaPoliticas.setColumns(20);
        jTextAreaPoliticas.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        jTextAreaPoliticas.setLineWrap(true);
        jTextAreaPoliticas.setRows(5);
        jScrollPane1.setViewportView(jTextAreaPoliticas);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 400, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelMinimizar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizar1MouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinimizar1MouseClicked

    private void jLabelBotonCerrar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotonCerrar1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabelBotonCerrar1MouseClicked

    private void jButtonRegresarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarMenuActionPerformed
        try {
            MenuCliente i = new MenuCliente();
            i.crear(administrador, cliente);
            this.setVisible(false);
            i.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(Politicas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonRegresarMenuActionPerformed

    private void jLabelMinimizar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizar2MouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinimizar2MouseClicked

    private void jLabelBotonCerrar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotonCerrar2MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabelBotonCerrar2MouseClicked

    private void jButtonRegresarMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarMenu1ActionPerformed
        MenuCliente i = new MenuCliente();
        try {
            i.crear(administrador, cliente);
        } catch (Exception ex) {
            Logger.getLogger(Politicas.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        i.setVisible(true);
    }//GEN-LAST:event_jButtonRegresarMenu1ActionPerformed

    public void llenar(Restaurante administrador){
        jTextAreaPoliticas.setText(administrador.getPoliticas());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Politicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Politicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Politicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Politicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Politicas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegresarMenu;
    private javax.swing.JButton jButtonRegresarMenu1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelBotonCerrar1;
    private javax.swing.JLabel jLabelBotonCerrar2;
    private javax.swing.JLabel jLabelMinimizar1;
    private javax.swing.JLabel jLabelMinimizar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaPoliticas;
    // End of variables declaration//GEN-END:variables
}
